# Generated by Django 4.1.3 on 2023-04-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='messageid_sseed',
            new_name='mesageid_sseed',
        ),
    ]
