# Generated by Django 4.1.3 on 2023-04-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_client_image_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tg_message_id',
            field=models.CharField(default=1234, max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
