# Generated by Django 4.1.3 on 2023-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_image_tg_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
