# Generated by Django 4.1.3 on 2023-04-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_image_updated_time_alter_image_messageid_sseed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
