# Generated by Django 4.1.3 on 2023-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_alter_image_tg_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tg_message_id',
            field=models.IntegerField(null=True),
        ),
    ]
