# Generated by Django 4.1.3 on 2023-04-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_alter_image_tg_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='messageid_sseed',
            new_name='mesageid_sseed',
        ),
    ]
