# Generated by Django 4.1.3 on 2023-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_rename_messageid_sseed_image_mesageid_sseed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mesageid_sseed',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
