# Generated by Django 4.1.3 on 2023-04-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_alter_image_mesageid_sseed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='prompt',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
